### ISSUE TITLE
Nice project. Please upgrade it to support Flutter 3.0

### ISSUE THREAD

**Issue by md-siam** [quangrau/flutter_kid_starter#2]
Nice project. Please upgrade it to support Flutter 3.0

**Comment by kalimaty** [comment]
Nice project. Please upgrade it to support Flutter 3.0

**Comment by md-siam** [comment]
> Nice project. Please upgrade it to support Flutter 3.0

Checkout this URL: https://github.com/md-siam/kid_starter
